name = "journal"
version = "0.1.0"
authors = ["Michael Zhang <mail@mzhang.io>"]
lua_entrypoint = "journal.lua"
qt_library = "dist/arm64-apple-darwin/libpanorama-journal.dylib"
permissions = ["privileged"]
lua_functions = ["openUrl"]

regexes = ["^/journal/"]

[fields]
"journal/title" = "TEXT"
"journal/content" = "TEXT"

[on]
self_loaded = "on_self_loaded"
plugins_loaded = "on_plugins_loaded"
