[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
axum = { version = "0.8.1", features = [
  "json",
  "http2",
  "macros",
  "ws",
  "multipart",
] }
futures = "0.3.31"
juniper = { version = "0.16.1", features = [
  "anyhow",
  "backtrace",
  "chrono",
  "chrono-tz",
] }
juniper_axum = { version = "0.2.0", features = ["subscriptions"] }
juniper_graphql_ws = "0.4.0"
rusqlite = { version = "0.32", features = ["functions"] }
sqlx = { version = "0.8.3", features = [
  "runtime-tokio",
  "tls-rustls",
  "sqlite",
  "chrono",
] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = "0.1.17"
uuid = { version = "1.12.1", features = ["v7"] }
chrono = "0.4.30"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tower-http = { version = "0.6.2", features = ["trace"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
icalendar = { version = "0.16.12", features = ["serde", "serde_json", "chrono-tz"] }
